### ISSUE TITLE
Lambda step fails sometimes

### ISSUE THREAD

**Issue by Berehulia** [bohdan-onsha/hackaton-syndicate-project-template#2]
2022-09-08 23:19:10,978 [INFO] USER:Mykyta deployment_processor.py:95:_process_resources LOG: Processing lambda resources
2022-09-08 23:22:45,512 [ERROR] USER:Mykyta deployment_processor.py:102:_process_resources LOG: Error occurred while lambda resource creating: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations
Traceback (most recent call last):
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\core\build\deployment_processor.py", line 97, in _process_resources
    response = func(args)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\core\resources\lambda_resource.py", line 129, in create_lambda
    return self.create_pool(self._create_lambda_from_meta, args)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\core\resources\base_resource.py", line 41, in create_pool
    result = future.result()
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\core\helper.py", line 64, in wrapper
    return handler_func(**parameters)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\connection\helper.py", line 88, in wrapper
    raise e
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\connection\helper.py", line 74, in wrapper
    return handler_func(*args, **kwargs)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\core\resources\lambda_resource.py", line 330, in _create_lambda_from_meta
    func(self, name, arn, role_name, trigger_meta)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\connection\helper.py", line 88, in wrapper
    raise e
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\connection\helper.py", line 74, in wrapper
    return handler_func(*args, **kwargs)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\core\resources\lambda_resource.py", line 701, in _create_s3_trigger_from_meta
    self.s3_conn.configure_event_source_for_lambda(target_bucket,
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\connection\helper.py", line 88, in wrapper
    raise e
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\connection\helper.py", line 74, in wrapper
    return handler_func(*args, **kwargs)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\syndicate\connection\s3_connection.py", line 198, in configure_event_source_for_lambda
    self.client.put_bucket_notification_configuration(
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\Mykyta\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations
2022-09-08 23:22:45,574 [INFO] USER:Mykyta deployment_processor.py:343:create_deployment_resources LOG: Going to create deploy output
2022-09-08 23:22:45,918 [INFO] USER:Mykyta deployment_processor.py:349:create_deployment_resources LOG: Deploy output for hackaton-syndicate-project-template was created.
Backend resources were deployed with errors. See deploy output file.

**Comment by Berehulia** [comment]
Works after:

In case of deployment errors:
Clean deployed resources: syndicate clean --rollback

Build syndicate build --errors_allowed

Deploy syndicate deploy
